### ISSUE TITLE
проблемма с работой скрипта при прокрутке вниз

### ISSUE THREAD

**Issue by skinysmn** [maximzhurkin/jquery-scrolla#1]
Здравствуйте, сломал голову, но таки не смог понять почему при прокрутке страницы ВВЕРХ все работает хорошо, но при прокрутке вниз анимация не запускается..
пример тут sms.enterin-sites.ru

**Comment by maximzhurkin** [comment]
Привет, не могу посмотреть( походу dns не обновились, может ip?

**Comment by skinysmn** [comment]
ошибочка в домене, извини.
sms.enterin-sites.tk

**Comment by maximzhurkin** [comment]
Попробуй добавить html, body { height: 100%; }

**Comment by skinysmn** [comment]
сработало!
спасибо.
