### ISSUE TITLE
Off-set Detection?

### ISSUE THREAD

**Issue by Jonathlee** [maximzhurkin/jquery-scrolla#2]
Any possibility to add in off-set detection?
Animation will only run after the subject visibility detected at 200px?

`data-offset="200px"`

![scrolla](https://cloud.githubusercontent.com/assets/696956/19631523/2f7ad5ec-99d0-11e6-92eb-63f5adfcc230.png)

**Comment by maximzhurkin** [comment]
Hi Jonathlee, data-offset attribute added

**Comment by Jonathlee** [comment]
Thank you very much. It the lightest plugins. Congrats Maximzhurkin
