### ISSUE TITLE
Issue with (visibility:hidden) scroll to top function.

### ISSUE THREAD

**Issue by sohrabzia** [maximzhurkin/jquery-scrolla#4]
I am using scroll to top function. when i scroll to top there is attribute added to div
 `'visibility:hidden;` ,  which is not showing empty space instead of div, i am using option (once: true)

**Comment by maximzhurkin** [comment]
Hi sohrabzia, I'm sorry, I did not understand problem. Please example. I sketched pen: http://codepen.io/maxzhurkin/pen/dObQob

**Comment by sohrabzia** [comment]
Hi. I don't know how but it is working perfectly now. thank you so much.
