### ISSUE TITLE
It won't work with version 4 of animate.css

### ISSUE THREAD

**Issue by Chocofede** [maximzhurkin/jquery-scrolla#8]
Hi Maxim, 

You created a quite useful plugin! I've been checking it, and it works like a charm with v 3.5 of animate.css, the one you have linked in the demo. However, the new version 4.0 of animate.css doesn't work with your plugin anymore. 

I guess that there was a change in the classes added, and due to that the plugin is not adding the proper classes. You may check https://animate.style/#migration, where it explains that now the classes must be:

"animate__animated" for the html element, 
"animate__ANIMATE-OPTION" for the data-animate. 

Adding that instead of only animated and ANIMATE-OPTION, Scrolla keeps working, but I think it would be worthy to mention in the Readme to help other people, :D.

**Comment by maximzhurkin** [comment]
thanks for the feedback! I added a new parameter "animateCssVersion"
`$('.animate').scrolla({
  animateCssVersion: 4 // used animate.css version (3 or 4)
});`

**Comment by Chocofede** [comment]
> thanks for the feedback! I added a new parameter "animateCssVersion"
> `$('.animate').scrolla({ animateCssVersion: 4 // used animate.css version (3 or 4) });`

Even better than mentioning it in the docs, :D
